export type MockNameData = {
  name: string;
  origin: string;
  personalizedReason: string;
};

export const mockNamesByType: Record<string, MockNameData[]> = {
  dog: [
    { name: "Apollo", origin: "Greek Mythology", personalizedReason: "Great for a radiant and noble dog" },
    { name: "Finn", origin: "Irish", personalizedReason: "Perfect for a light-colored, energetic pup" },
    { name: "Ranger", origin: "English", personalizedReason: "Ideal for an adventurous and loyal companion" },
    { name: "Atlas", origin: "Greek Mythology", personalizedReason: "Perfect for a loyal and strong dog who carries your heart" },
    { name: "Sage", origin: "Latin", personalizedReason: "Ideal for an intelligent and intuitive canine companion" },
    { name: "Nova", origin: "Latin", personalizedReason: "Beautiful for a dog who brings light and energy to your life" },
    { name: "Luna", origin: "Latin", personalizedReason: "Perfect for a dog who lights up your darkest nights" },
    { name: "Zeus", origin: "Greek Mythology", personalizedReason: "Ideal for a majestic and protective dog" },
    { name: "Milo", origin: "Germanic", personalizedReason: "Great for a gentle yet brave companion" },
    { name: "Bailey", origin: "English", personalizedReason: "Great for a dependable and watchful dog" },
    { name: "Echo", origin: "Greek", personalizedReason: "Fun for a responsive and vocal dog" },
    { name: "Cleo", origin: "Greek", personalizedReason: "For a confident and regal dog" },
    { name: "Aspen", origin: "English", personalizedReason: "Fitting for a nature-loving, brave pup" },
    { name: "Hunter", origin: "English", personalizedReason: "Ideal for an energetic and curious dog" },
    { name: "Leo", origin: "Latin", personalizedReason: "Great for a bold and brave dog" },
    { name: "Rusty", origin: "English", personalizedReason: "Perfect for a reddish-coated companion" },
    { name: "Shadow", origin: "English", personalizedReason: "Ideal for a loyal and quiet dog" },
    { name: "Bear", origin: "Old English", personalizedReason: "Fitting for a large, cuddly companion" },
    { name: "Blue", origin: "English", personalizedReason: "Nice for a serene and composed dog" },
    { name: "Scout", origin: "French", personalizedReason: "Great for a curious and clever explorer" }
  ],

  cat: [
    { name: "Nyx", origin: "Greek Mythology", personalizedReason: "Perfect for a sleek and mysterious feline" },
    { name: "Sable", origin: "French", personalizedReason: "Ideal for a dark-coated elegant cat" },
    { name: "Mochi", origin: "Japanese", personalizedReason: "Cute and squishy name for a lovable cat" },
    { name: "Vesper", origin: "Latin", personalizedReason: "Perfect for a mysterious and graceful feline" },
    { name: "Juniper", origin: "Celtic", personalizedReason: "Wonderful for a playful and spirited cat" },
    { name: "Onyx", origin: "Greek", personalizedReason: "Ideal for a sleek, dark-coated cat with presence" },
    { name: "Luna", origin: "Latin", personalizedReason: "Perfect for a peaceful, night-loving cat" },
    { name: "Salem", origin: "Hebrew", personalizedReason: "Great for a calm, independent feline" },
    { name: "Nimbus", origin: "Latin", personalizedReason: "Soft name for a quiet and dreamy cat" },
    { name: "Cinder", origin: "English", personalizedReason: "Fitting for a smoky-colored mysterious cat" },
    { name: "Maple", origin: "English", personalizedReason: "Beautiful for a gentle and curious cat" },
    { name: "Indigo", origin: "Greek", personalizedReason: "Wonderful for a unique and artistic feline" },
    { name: "Miso", origin: "Japanese", personalizedReason: "Adorable name for a small and savory companion" },
    { name: "Basil", origin: "Greek", personalizedReason: "Perfect for a dignified and charming cat" },
    { name: "Velvet", origin: "English", personalizedReason: "Ideal for a cuddly and soft-furred cat" },
    { name: "Echo", origin: "Greek", personalizedReason: "Lovely for a talkative or responsive cat" },
    { name: "Whisker", origin: "English", personalizedReason: "Cute and playful name for any cat" },
    { name: "Fig", origin: "English", personalizedReason: "Sweet and compact name for a loving cat" },
    { name: "Ash", origin: "Old English", personalizedReason: "Perfect for a gray or quiet cat" },
    { name: "Raven", origin: "English", personalizedReason: "Great for a sleek and observant feline" }
  ],

  horse: [
    { name: "Thunder", origin: "Germanic", personalizedReason: "Ideal for a horse with a bold and dynamic spirit" },
    { name: "Willow", origin: "Old English", personalizedReason: "Perfect for a gentle, flowing horse with an adaptable nature" },
    { name: "Ember", origin: "Old English", personalizedReason: "Beautiful for a horse with a fiery spirit and warm personality" },
    { name: "Blaze", origin: "English", personalizedReason: "Ideal for a spirited and fast horse" },
    { name: "Storm", origin: "English", personalizedReason: "Perfect for a powerful and dynamic horse" },
    { name: "Dakota", origin: "Sioux", personalizedReason: "Wonderful for a loyal and majestic horse" },
    { name: "Shadow", origin: "English", personalizedReason: "Great for a mysterious and elegant horse" },
    { name: "Spirit", origin: "English", personalizedReason: "Perfect for a wild and free-spirited horse" },
    { name: "Comet", origin: "Latin", personalizedReason: "For a fast and luminous horse" },
    { name: "Aurora", origin: "Latin", personalizedReason: "Ideal for a horse with a gentle and beautiful presence" },
    { name: "Cinder", origin: "English", personalizedReason: "Great for a smoky-colored, strong horse" },
    { name: "Breeze", origin: "English", personalizedReason: "Perfect for a calm and graceful horse" },
    { name: "Apollo", origin: "Greek Mythology", personalizedReason: "For a majestic and noble horse" },
    { name: "Titan", origin: "Greek Mythology", personalizedReason: "Fitting for a strong and bold horse" },
    { name: "Nova", origin: "Latin", personalizedReason: "Ideal for a horse that shines in spirit and beauty" },
    { name: "Sable", origin: "French", personalizedReason: "Perfect for a sleek, elegant horse" },
    { name: "Indigo", origin: "Greek", personalizedReason: "Great for a unique and striking horse" },
    { name: "Ash", origin: "Old English", personalizedReason: "Beautiful for a calm, gray horse" },
    { name: "Stormy", origin: "English", personalizedReason: "Fitting for a dynamic, spirited horse" },
    { name: "Echo", origin: "Greek Mythology", personalizedReason: "Ideal for a responsive and attentive horse" }
  ],

  rabbit: [
    { name: "Clover", origin: "English", personalizedReason: "Perfect for a lucky bunny who brings joy to your life" },
    { name: "Thistle", origin: "Scottish", personalizedReason: "Great for a strong-willed and adventurous rabbit" },
    { name: "Hazel", origin: "English", personalizedReason: "Sweet name for a calm and gentle rabbit" },
    { name: "Bramble", origin: "English", personalizedReason: "Perfect for a curious and exploring bunny" },
    { name: "Snowball", origin: "English", personalizedReason: "Great for a soft, white rabbit" },
    { name: "Peaches", origin: "English", personalizedReason: "Lovely for a sweet and playful bunny" },
    { name: "Daisy", origin: "English", personalizedReason: "Perfect for a gentle and cute rabbit" },
    { name: "Pumpkin", origin: "English", personalizedReason: "Great for a chubby or orange-colored rabbit" },
    { name: "Cotton", origin: "English", personalizedReason: "Ideal for a fluffy and cuddly rabbit" },
    { name: "Maple", origin: "English", personalizedReason: "Perfect for a friendly rabbit" },
    { name: "Peanut", origin: "English", personalizedReason: "Cute name for a tiny rabbit" },
    { name: "Marshmallow", origin: "English", personalizedReason: "Great for a soft, sweet bunny" },
    { name: "Cinnamon", origin: "English", personalizedReason: "Perfect for a warm-colored rabbit" },
    { name: "Acorn", origin: "English", personalizedReason: "Ideal for a small and energetic rabbit" },
    { name: "Biscuit", origin: "English", personalizedReason: "Cute and playful rabbit name" },
    { name: "Ginger", origin: "English", personalizedReason: "Perfect for a ginger-colored bunny" },
    { name: "Muffin", origin: "English", personalizedReason: "Adorable name for a sweet rabbit" },
    { name: "Pebble", origin: "English", personalizedReason: "Ideal for a tiny or quiet rabbit" },
    { name: "Twinkle", origin: "English", personalizedReason: "Great for a lively and joyful bunny" },
    { name: "Fawn", origin: "English", personalizedReason: "Perfect for a gentle, light-colored rabbit" }
  ],

  fish: [
    { name: "Azure", origin: "Persian/Arabic", personalizedReason: "Perfect for a vibrant fish with beautiful blue hues" },
    { name: "Coral", origin: "Greek", personalizedReason: "Ideal for a colorful fish bringing life to your aquarium" },
    { name: "Neon", origin: "Greek", personalizedReason: "Perfect for a vibrant and flashy fish" },
    { name: "Splash", origin: "English", personalizedReason: "Fun name for a lively swimmer" },
    { name: "Lapis", origin: "Latin", personalizedReason: "Ideal for a deep blue aquatic beauty" },
    { name: "Finley", origin: "Irish", personalizedReason: "Great for a playful fish" },
    { name: "Bubbles", origin: "English", personalizedReason: "Perfect for a fun and cheerful fish" },
    { name: "Marlin", origin: "English", personalizedReason: "Ideal for a swift swimmer" },
    { name: "Dory", origin: "Greek", personalizedReason: "Cute and memorable fish name" },
    { name: "Pearl", origin: "Latin", personalizedReason: "Beautiful for a white or shiny fish" },
    { name: "Splashy", origin: "English", personalizedReason: "Fun for an active fish" },
    { name: "Reef", origin: "English", personalizedReason: "Great for a colorful aquarium fish" },
    { name: "Aqua", origin: "Latin", personalizedReason: "Perfect for a serene water-loving fish" },
    { name: "Wave", origin: "English", personalizedReason: "Ideal for a graceful fish" },
    { name: "Cobalt", origin: "German", personalizedReason: "Perfect for a blue-hued fish" },
    { name: "Sunny", origin: "English", personalizedReason: "For a cheerful and lively fish" },
    { name: "Ripple", origin: "English", personalizedReason: "Ideal for a calm-moving fish" },
    { name: "Glint", origin: "English", personalizedReason: "Perfect for a shiny, reflective fish" },
    { name: "Neptune", origin: "Roman Mythology", personalizedReason: "Majestic name for a regal fish" },
    { name: "Tide", origin: "English", personalizedReason: "For a flowing, graceful fish" }
  ],

  other: [
    { name: "Echo", origin: "Greek Mythology", personalizedReason: "Perfect for a pet who's always in tune with your emotions" },
    { name: "Phoenix", origin: "Greek Mythology", personalizedReason: "Ideal for a pet representing new beginnings and transformation" },
    { name: "Cosmos", origin: "Greek", personalizedReason: "Beautiful for a pet who brings order and wonder to your world" },
    { name: "Zephyr", origin: "Greek", personalizedReason: "Perfect for a breezy and calm animal" },
    { name: "Orion", origin: "Greek Mythology", personalizedReason: "Ideal for a pet with star quality" },
    { name: "Nimbus", origin: "Latin", personalizedReason: "Great for a gentle, dreamy pet" },
    { name: "Comet", origin: "Latin", personalizedReason: "Perfect for a fast and luminous pet" },
    { name: "Aurora", origin: "Latin", personalizedReason: "Ideal for a pet who brings light and beauty" },
    { name: "Myst", origin: "English", personalizedReason: "Great for a mysterious and elusive pet" },
    { name: "Ember", origin: "Old English", personalizedReason: "Perfect for a fiery and warm pet" },
    { name: "Sirius", origin: "Greek", personalizedReason: "Ideal for a shining, outstanding pet" },
    { name: "Lumen", origin: "Latin", personalizedReason: "Great for a pet who brightens your life" },
    { name: "Shadow", origin: "English", personalizedReason: "Perfect for a quiet and loyal pet" },
    { name: "Indigo", origin: "Greek", personalizedReason: "Great for a unique and calm pet" },
    { name: "Fable", origin: "English", personalizedReason: "Ideal for a pet with a magical personality" },
    { name: "Nova", origin: "Latin", personalizedReason: "Perfect for a fresh and bright presence" },
    { name: "Galaxy", origin: "Greek", personalizedReason: "Great for a vast and wondrous pet" },
    { name: "Auric", origin: "Latin", personalizedReason: "Ideal for a warm and radiant pet" },
    { name: "Quest", origin: "English", personalizedReason: "Perfect for a curious and adventurous pet" },
    { name: "Rune", origin: "Old Norse", personalizedReason: "Great for a pet with a magical aura" }
  ]
};