export type MockNameData = {
  name: string;
  origin: string;
  meaning: string;
  personalizedReason: string;
};

export const mockNamesByType: Record<string, MockNameData[]> = {
  dog: [
    { name: "Apollo", origin: "Greek Mythology", meaning: "God of the sun, music, and prophecy", personalizedReason: "Great for a radiant and noble dog" },
    { name: "Finn", origin: "Irish", meaning: "Fair or white", personalizedReason: "Perfect for a light-colored, energetic pup" },
    { name: "Ranger", origin: "English", meaning: "Forest guardian", personalizedReason: "Ideal for an adventurous and loyal companion" },
    { name: "Atlas", origin: "Greek Mythology", meaning: "Bearer of the heavens, symbolizing strength and endurance", personalizedReason: "Perfect for a loyal and strong dog who carries your heart" },
    { name: "Sage", origin: "Latin", meaning: "Wise one, representing wisdom and clarity", personalizedReason: "Ideal for an intelligent and intuitive canine companion" },
    { name: "Nova", origin: "Latin", meaning: "New star, symbolizing brightness and new beginnings", personalizedReason: "Beautiful for a dog who brings light and energy to your life" },
    { name: "Luna", origin: "Latin", meaning: "Moon, symbolizing mystery and guidance", personalizedReason: "Perfect for a dog who lights up your darkest nights" },
    { name: "Zeus", origin: "Greek Mythology", meaning: "King of the gods, symbolizing leadership and protection", personalizedReason: "Ideal for a majestic and protective dog" },
    { name: "Milo", origin: "Germanic", meaning: "Merciful, gracious, or soldier", personalizedReason: "Great for a gentle yet brave companion" },
    { name: "Bailey", origin: "English", meaning: "Trusted guardian", personalizedReason: "Great for a dependable and watchful dog" },
    { name: "Echo", origin: "Greek", meaning: "Resonating sound", personalizedReason: "Fun for a responsive and vocal dog" },
    { name: "Cleo", origin: "Greek", meaning: "Pride, fame", personalizedReason: "For a confident and regal dog" },
    { name: "Aspen", origin: "English", meaning: "Tree of courage", personalizedReason: "Fitting for a nature-loving, brave pup" },
    { name: "Hunter", origin: "English", meaning: "One who hunts", personalizedReason: "Ideal for an energetic and curious dog" },
    { name: "Leo", origin: "Latin", meaning: "Lion", personalizedReason: "Great for a bold and brave dog" },
    { name: "Rusty", origin: "English", meaning: "Red-haired", personalizedReason: "Perfect for a reddish-coated companion" },
    { name: "Shadow", origin: "English", meaning: "Silent follower", personalizedReason: "Ideal for a loyal and quiet dog" },
    { name: "Bear", origin: "Old English", meaning: "Strong and brave", personalizedReason: "Fitting for a large, cuddly companion" },
    { name: "Blue", origin: "English", meaning: "Color blue, symbolizing calm and coolness", personalizedReason: "Nice for a serene and composed dog" },
    { name: "Scout", origin: "French", meaning: "One who gathers information", personalizedReason: "Great for a curious and clever explorer" }
  ],

  cat: [
    { name: "Nyx", origin: "Greek Mythology", meaning: "Goddess of the night", personalizedReason: "Perfect for a sleek and mysterious feline" },
    { name: "Sable", origin: "French", meaning: "Black fur", personalizedReason: "Ideal for a dark-coated elegant cat" },
    { name: "Mochi", origin: "Japanese", meaning: "Soft rice cake", personalizedReason: "Cute and squishy name for a lovable cat" },
    { name: "Vesper", origin: "Latin", meaning: "Evening star, associated with mystery and elegance", personalizedReason: "Perfect for a mysterious and graceful feline" },
    { name: "Juniper", origin: "Celtic", meaning: "Young and evergreen, symbolizing protection and vitality", personalizedReason: "Wonderful for a playful and spirited cat" },
    { name: "Onyx", origin: "Greek", meaning: "Black gem, representing protection and strength", personalizedReason: "Ideal for a sleek, dark-coated cat with presence" },
    { name: "Luna", origin: "Latin", meaning: "Moon, symbolizing calmness and glow", personalizedReason: "Perfect for a peaceful, night-loving cat" },
    { name: "Salem", origin: "Hebrew", meaning: "Peace", personalizedReason: "Great for a calm, independent feline" },
    { name: "Nimbus", origin: "Latin", meaning: "Rain cloud", personalizedReason: "Soft name for a quiet and dreamy cat" },
    { name: "Cinder", origin: "English", meaning: "Ash or ember", personalizedReason: "Fitting for a smoky-colored mysterious cat" },
    { name: "Maple", origin: "English", meaning: "Maple tree, symbolizing grace and beauty", personalizedReason: "Beautiful for a gentle and curious cat" },
    { name: "Indigo", origin: "Greek", meaning: "Deep blue-purple color", personalizedReason: "Wonderful for a unique and artistic feline" },
    { name: "Miso", origin: "Japanese", meaning: "Fermented bean paste", personalizedReason: "Adorable name for a small and savory companion" },
    { name: "Basil", origin: "Greek", meaning: "Royal or kingly", personalizedReason: "Perfect for a dignified and charming cat" },
    { name: "Velvet", origin: "English", meaning: "Soft and smooth", personalizedReason: "Ideal for a cuddly and soft-furred cat" },
    { name: "Echo", origin: "Greek", meaning: "Sound reverberation", personalizedReason: "Lovely for a talkative or responsive cat" },
    { name: "Whisker", origin: "English", meaning: "Cat's facial hair", personalizedReason: "Cute and playful name for any cat" },
    { name: "Fig", origin: "English", meaning: "Sweet fruit", personalizedReason: "Sweet and compact name for a loving cat" },
    { name: "Ash", origin: "Old English", meaning: "Tree or gray residue", personalizedReason: "Perfect for a gray or quiet cat" },
    { name: "Raven", origin: "English", meaning: "Black bird, symbol of mystery", personalizedReason: "Great for a sleek and observant feline" }
  ],

  horse: [
    { name: "Thunder", origin: "Germanic", meaning: "Symbolizes power and strength, evoking the energy of a storm", personalizedReason: "Ideal for a horse with a bold and dynamic spirit" },
    { name: "Willow", origin: "Old English", meaning: "Represents flexibility and grace, inspired by the willow tree", personalizedReason: "Perfect for a gentle, flowing horse with an adaptable nature" },
    { name: "Ember", origin: "Old English", meaning: "Glowing coal, symbolizing inner fire and warmth", personalizedReason: "Beautiful for a horse with a fiery spirit and warm personality" },
    { name: "Blaze", origin: "English", meaning: "Flame or fire", personalizedReason: "Ideal for a spirited and fast horse" },
    { name: "Storm", origin: "English", meaning: "Strong weather, power", personalizedReason: "Perfect for a powerful and dynamic horse" },
    { name: "Dakota", origin: "Sioux", meaning: "Friendly companion", personalizedReason: "Wonderful for a loyal and majestic horse" },
    { name: "Shadow", origin: "English", meaning: "Dark companion", personalizedReason: "Great for a mysterious and elegant horse" },
    { name: "Spirit", origin: "English", meaning: "Freedom and energy", personalizedReason: "Perfect for a wild and free-spirited horse" },
    { name: "Comet", origin: "Latin", meaning: "A celestial body", personalizedReason: "For a fast and luminous horse" },
    { name: "Aurora", origin: "Latin", meaning: "Dawn", personalizedReason: "Ideal for a horse with a gentle and beautiful presence" },
    { name: "Cinder", origin: "English", meaning: "Ash from fire", personalizedReason: "Great for a smoky-colored, strong horse" },
    { name: "Breeze", origin: "English", meaning: "Gentle wind", personalizedReason: "Perfect for a calm and graceful horse" },
    { name: "Apollo", origin: "Greek Mythology", meaning: "God of music and sun", personalizedReason: "For a majestic and noble horse" },
    { name: "Titan", origin: "Greek Mythology", meaning: "Powerful giant", personalizedReason: "Fitting for a strong and bold horse" },
    { name: "Nova", origin: "Latin", meaning: "New star", personalizedReason: "Ideal for a horse that shines in spirit and beauty" },
    { name: "Sable", origin: "French", meaning: "Dark fur", personalizedReason: "Perfect for a sleek, elegant horse" },
    { name: "Indigo", origin: "Greek", meaning: "Deep blue", personalizedReason: "Great for a unique and striking horse" },
    { name: "Ash", origin: "Old English", meaning: "Tree or gray", personalizedReason: "Beautiful for a calm, gray horse" },
    { name: "Stormy", origin: "English", meaning: "Wild weather", personalizedReason: "Fitting for a dynamic, spirited horse" },
    { name: "Echo", origin: "Greek Mythology", meaning: "Sound reverberation", personalizedReason: "Ideal for a responsive and attentive horse" }
  ],

  rabbit: [
    { name: "Clover", origin: "English", meaning: "Symbol of luck and prosperity", personalizedReason: "Perfect for a lucky bunny who brings joy to your life" },
    { name: "Thistle", origin: "Scottish", meaning: "Resilient flower, symbolizing protection and nobility", personalizedReason: "Great for a strong-willed and adventurous rabbit" },
    { name: "Hazel", origin: "English", meaning: "The hazel tree", personalizedReason: "Sweet name for a calm and gentle rabbit" },
    { name: "Bramble", origin: "English", meaning: "Wild shrub", personalizedReason: "Perfect for a curious and exploring bunny" },
    { name: "Snowball", origin: "English", meaning: "White and fluffy", personalizedReason: "Great for a soft, white rabbit" },
    { name: "Peaches", origin: "English", meaning: "Fruit, sweet and soft", personalizedReason: "Lovely for a sweet and playful bunny" },
    { name: "Daisy", origin: "English", meaning: "Flower symbolizing innocence", personalizedReason: "Perfect for a gentle and cute rabbit" },
    { name: "Pumpkin", origin: "English", meaning: "Orange fruit", personalizedReason: "Great for a chubby or orange-colored rabbit" },
    { name: "Cotton", origin: "English", meaning: "Soft fiber", personalizedReason: "Ideal for a fluffy and cuddly rabbit" },
    { name: "Maple", origin: "English", meaning: "Tree, symbolizes warmth", personalizedReason: "Perfect for a friendly rabbit" },
    { name: "Peanut", origin: "English", meaning: "Small nut", personalizedReason: "Cute name for a tiny rabbit" },
    { name: "Marshmallow", origin: "English", meaning: "Soft candy", personalizedReason: "Great for a soft, sweet bunny" },
    { name: "Cinnamon", origin: "English", meaning: "Spice, warm brown", personalizedReason: "Perfect for a warm-colored rabbit" },
    { name: "Acorn", origin: "English", meaning: "Oak seed", personalizedReason: "Ideal for a small and energetic rabbit" },
    { name: "Biscuit", origin: "English", meaning: "Soft bread", personalizedReason: "Cute and playful rabbit name" },
    { name: "Ginger", origin: "English", meaning: "Spicy root, orange color", personalizedReason: "Perfect for a ginger-colored bunny" },
    { name: "Muffin", origin: "English", meaning: "Soft baked treat", personalizedReason: "Adorable name for a sweet rabbit" },
    { name: "Pebble", origin: "English", meaning: "Small stone", personalizedReason: "Ideal for a tiny or quiet rabbit" },
    { name: "Twinkle", origin: "English", meaning: "Sparkle or shine", personalizedReason: "Great for a lively and joyful bunny" },
    { name: "Fawn", origin: "English", meaning: "Young deer", personalizedReason: "Perfect for a gentle, light-colored rabbit" }
  ],

  fish: [
    { name: "Azure", origin: "Persian/Arabic", meaning: "Blue color of the sky and sea", personalizedReason: "Perfect for a vibrant fish with beautiful blue hues" },
    { name: "Coral", origin: "Greek", meaning: "From the sea, symbolizing beauty and protection", personalizedReason: "Ideal for a colorful fish bringing life to your aquarium" },
    { name: "Neon", origin: "Greek", meaning: "Bright or glowing", personalizedReason: "Perfect for a vibrant and flashy fish" },
    { name: "Splash", origin: "English", meaning: "Water splash", personalizedReason: "Fun name for a lively swimmer" },
    { name: "Lapis", origin: "Latin", meaning: "Blue stone", personalizedReason: "Ideal for a deep blue aquatic beauty" },
    { name: "Finley", origin: "Irish", meaning: "Fair-haired hero", personalizedReason: "Great for a playful fish" },
    { name: "Bubbles", origin: "English", meaning: "Air in water", personalizedReason: "Perfect for a fun and cheerful fish" },
    { name: "Marlin", origin: "English", meaning: "Fast ocean fish", personalizedReason: "Ideal for a swift swimmer" },
    { name: "Dory", origin: "Greek", meaning: "Gift", personalizedReason: "Cute and memorable fish name" },
    { name: "Pearl", origin: "Latin", meaning: "Gem from oyster", personalizedReason: "Beautiful for a white or shiny fish" },
    { name: "Splashy", origin: "English", meaning: "Splash enthusiast", personalizedReason: "Fun for an active fish" },
    { name: "Reef", origin: "English", meaning: "Coral reef", personalizedReason: "Great for a colorful aquarium fish" },
    { name: "Aqua", origin: "Latin", meaning: "Water", personalizedReason: "Perfect for a serene water-loving fish" },
    { name: "Wave", origin: "English", meaning: "Ocean wave", personalizedReason: "Ideal for a graceful fish" },
    { name: "Cobalt", origin: "German", meaning: "Deep blue metal", personalizedReason: "Perfect for a blue-hued fish" },
    { name: "Sunny", origin: "English", meaning: "Bright like the sun", personalizedReason: "For a cheerful and lively fish" },
    { name: "Ripple", origin: "English", meaning: "Water motion", personalizedReason: "Ideal for a calm-moving fish" },
    { name: "Glint", origin: "English", meaning: "Sparkle", personalizedReason: "Perfect for a shiny, reflective fish" },
    { name: "Neptune", origin: "Roman Mythology", meaning: "God of the sea", personalizedReason: "Majestic name for a regal fish" },
    { name: "Tide", origin: "English", meaning: "Ocean movement", personalizedReason: "For a flowing, graceful fish" }
  ],

  other: [
    { name: "Echo", origin: "Greek Mythology", meaning: "Resonating sound, symbolizing connection and response", personalizedReason: "Perfect for a pet who's always in tune with your emotions" },
    { name: "Phoenix", origin: "Greek Mythology", meaning: "Mythical bird of renewal and rebirth", personalizedReason: "Ideal for a pet representing new beginnings and transformation" },
    { name: "Cosmos", origin: "Greek", meaning: "Universe or harmony, representing infinite possibilities", personalizedReason: "Beautiful for a pet who brings order and wonder to your world" },
    { name: "Zephyr", origin: "Greek", meaning: "West wind", personalizedReason: "Perfect for a breezy and calm animal" },
    { name: "Orion", origin: "Greek Mythology", meaning: "Hunter constellation", personalizedReason: "Ideal for a pet with star quality" },
    { name: "Nimbus", origin: "Latin", meaning: "Rain cloud", personalizedReason: "Great for a gentle, dreamy pet" },
    { name: "Comet", origin: "Latin", meaning: "Celestial body", personalizedReason: "Perfect for a fast and luminous pet" },
    { name: "Aurora", origin: "Latin", meaning: "Dawn, northern lights", personalizedReason: "Ideal for a pet who brings light and beauty" },
    { name: "Myst", origin: "English", meaning: "Fog or mystery", personalizedReason: "Great for a mysterious and elusive pet" },
    { name: "Ember", origin: "Old English", meaning: "Glowing coal", personalizedReason: "Perfect for a fiery and warm pet" },
    { name: "Sirius", origin: "Greek", meaning: "Brightest star", personalizedReason: "Ideal for a shining, outstanding pet" },
    { name: "Lumen", origin: "Latin", meaning: "Light", personalizedReason: "Great for a pet who brightens your life" },
    { name: "Shadow", origin: "English", meaning: "Dark companion", personalizedReason: "Perfect for a quiet and loyal pet" },
    { name: "Indigo", origin: "Greek", meaning: "Deep blue", personalizedReason: "Great for a unique and calm pet" },
    { name: "Fable", origin: "English", meaning: "Story or legend", personalizedReason: "Ideal for a pet with a magical personality" },
    { name: "Nova", origin: "Latin", meaning: "New star", personalizedReason: "Perfect for a fresh and bright presence" },
    { name: "Galaxy", origin: "Greek", meaning: "Milky Way, universe", personalizedReason: "Great for a vast and wondrous pet" },
    { name: "Auric", origin: "Latin", meaning: "Golden", personalizedReason: "Ideal for a warm and radiant pet" },
    { name: "Quest", origin: "English", meaning: "Journey or adventure", personalizedReason: "Perfect for a curious and adventurous pet" },
    { name: "Rune", origin: "Old Norse", meaning: "Mystical symbol", personalizedReason: "Great for a pet with a magical aura" }
  ]
};
