export type MockNameData = {
  name: string;
  origin: string;
  meaning: string;
};

export const mockNamesByType: Record<string, MockNameData[]> = {
  dog: [
    { name: "Apollo", origin: "Greek Mythology", meaning: "God of the sun, music, and prophecy" },
    { name: "Finn", origin: "Irish", meaning: "Fair or white" },
    { name: "Ranger", origin: "English", meaning: "Forest guardian" },
    { name: "Atlas", origin: "Greek Mythology", meaning: "Bearer of the heavens, symbolizing strength and endurance" },
    { name: "Sage", origin: "Latin", meaning: "Wise one, representing wisdom and clarity" },
    { name: "Nova", origin: "Latin", meaning: "New star, symbolizing brightness and new beginnings" },
    { name: "Luna", origin: "Latin", meaning: "Moon, symbolizing mystery and guidance" },
    { name: "Zeus", origin: "Greek Mythology", meaning: "King of the gods, symbolizing leadership and protection" },
    { name: "Milo", origin: "Germanic", meaning: "Merciful, gracious, or soldier" },
    { name: "Bailey", origin: "English", meaning: "Trusted guardian" },
    { name: "Echo", origin: "Greek", meaning: "Resonating sound" },
    { name: "Cleo", origin: "Greek", meaning: "Pride, fame" },
    { name: "Aspen", origin: "English", meaning: "Tree of courage" },
    { name: "Hunter", origin: "English", meaning: "One who hunts" },
    { name: "Leo", origin: "Latin", meaning: "Lion" },
    { name: "Rusty", origin: "English", meaning: "Red-haired" },
    { name: "Shadow", origin: "English", meaning: "Silent follower" },
    { name: "Bear", origin: "Old English", meaning: "Strong and brave" },
    { name: "Blue", origin: "English", meaning: "Color blue, symbolizing calm and coolness" },
    { name: "Scout", origin: "French", meaning: "One who gathers information" }
  ],

  cat: [
    { name: "Nyx", origin: "Greek Mythology", meaning: "Goddess of the night" },
    { name: "Sable", origin: "French", meaning: "Black fur" },
    { name: "Mochi", origin: "Japanese", meaning: "Soft rice cake" },
    { name: "Vesper", origin: "Latin", meaning: "Evening star, associated with mystery and elegance" },
    { name: "Juniper", origin: "Celtic", meaning: "Young and evergreen, symbolizing protection and vitality" },
    { name: "Onyx", origin: "Greek", meaning: "Black gem, representing protection and strength" },
    { name: "Luna", origin: "Latin", meaning: "Moon, symbolizing calmness and glow" },
    { name: "Salem", origin: "Hebrew", meaning: "Peace" },
    { name: "Nimbus", origin: "Latin", meaning: "Rain cloud" },
    { name: "Cinder", origin: "English", meaning: "Ash or ember" },
    { name: "Maple", origin: "English", meaning: "Maple tree, symbolizing grace and beauty" },
    { name: "Indigo", origin: "Greek", meaning: "Deep blue-purple color" },
    { name: "Miso", origin: "Japanese", meaning: "Fermented bean paste" },
    { name: "Basil", origin: "Greek", meaning: "Royal or kingly" },
    { name: "Velvet", origin: "English", meaning: "Soft and smooth" },
    { name: "Echo", origin: "Greek", meaning: "Sound reverberation" },
    { name: "Whisker", origin: "English", meaning: "Cat's facial hair" },
    { name: "Fig", origin: "English", meaning: "Sweet fruit" },
    { name: "Ash", origin: "Old English", meaning: "Tree or gray residue" },
    { name: "Raven", origin: "English", meaning: "Black bird, symbol of mystery" }
  ],

  horse: [
    { name: "Thunder", origin: "Germanic", meaning: "Symbolizes power and strength, evoking the energy of a storm" },
    { name: "Willow", origin: "Old English", meaning: "Represents flexibility and grace, inspired by the willow tree" },
    { name: "Ember", origin: "Old English", meaning: "Glowing coal, symbolizing inner fire and warmth" },
    { name: "Blaze", origin: "English", meaning: "Flame or fire" },
    { name: "Storm", origin: "English", meaning: "Strong weather, power" },
    { name: "Dakota", origin: "Sioux", meaning: "Friendly companion" },
    { name: "Shadow", origin: "English", meaning: "Dark companion" },
    { name: "Spirit", origin: "English", meaning: "Freedom and energy" },
    { name: "Comet", origin: "Latin", meaning: "A celestial body" },
    { name: "Aurora", origin: "Latin", meaning: "Dawn" },
    { name: "Cinder", origin: "English", meaning: "Ash from fire" },
    { name: "Breeze", origin: "English", meaning: "Gentle wind" },
    { name: "Apollo", origin: "Greek Mythology", meaning: "God of music and sun" },
    { name: "Titan", origin: "Greek Mythology", meaning: "Powerful giant" },
    { name: "Nova", origin: "Latin", meaning: "New star" },
    { name: "Sable", origin: "French", meaning: "Dark fur" },
    { name: "Indigo", origin: "Greek", meaning: "Deep blue" },
    { name: "Ash", origin: "Old English", meaning: "Tree or gray" },
    { name: "Stormy", origin: "English", meaning: "Wild weather" },
    { name: "Echo", origin: "Greek Mythology", meaning: "Sound reverberation" }
  ],

  rabbit: [
    { name: "Clover", origin: "English", meaning: "Symbol of luck and prosperity" },
    { name: "Thistle", origin: "Scottish", meaning: "Resilient flower, symbolizing protection and nobility" },
    { name: "Hazel", origin: "English", meaning: "The hazel tree" },
    { name: "Bramble", origin: "English", meaning: "Wild shrub" },
    { name: "Snowball", origin: "English", meaning: "White and fluffy" },
    { name: "Peaches", origin: "English", meaning: "Fruit, sweet and soft" },
    { name: "Daisy", origin: "English", meaning: "Flower symbolizing innocence" },
    { name: "Pumpkin", origin: "English", meaning: "Orange fruit" },
    { name: "Cotton", origin: "English", meaning: "Soft fiber" },
    { name: "Maple", origin: "English", meaning: "Tree, symbolizes warmth" },
    { name: "Peanut", origin: "English", meaning: "Small nut" },
    { name: "Marshmallow", origin: "English", meaning: "Soft candy" },
    { name: "Cinnamon", origin: "English", meaning: "Spice, warm brown" },
    { name: "Acorn", origin: "English", meaning: "Oak seed" },
    { name: "Biscuit", origin: "English", meaning: "Soft bread" },
    { name: "Ginger", origin: "English", meaning: "Spicy root, orange color" },
    { name: "Muffin", origin: "English", meaning: "Soft baked treat" },
    { name: "Pebble", origin: "English", meaning: "Small stone" },
    { name: "Twinkle", origin: "English", meaning: "Sparkle or shine" },
    { name: "Fawn", origin: "English", meaning: "Young deer" }
  ],

  fish: [
    { name: "Azure", origin: "Persian/Arabic", meaning: "Blue color of the sky and sea" },
    { name: "Coral", origin: "Greek", meaning: "From the sea, symbolizing beauty and protection" },
    { name: "Neon", origin: "Greek", meaning: "Bright or glowing" },
    { name: "Splash", origin: "English", meaning: "Water splash" },
    { name: "Lapis", origin: "Latin", meaning: "Blue stone" },
    { name: "Finley", origin: "Irish", meaning: "Fair-haired hero" },
    { name: "Bubbles", origin: "English", meaning: "Air in water" },
    { name: "Marlin", origin: "English", meaning: "Fast ocean fish" },
    { name: "Dory", origin: "Greek", meaning: "Gift" },
    { name: "Pearl", origin: "Latin", meaning: "Gem from oyster" },
    { name: "Splashy", origin: "English", meaning: "Splash enthusiast" },
    { name: "Reef", origin: "English", meaning: "Coral reef" },
    { name: "Aqua", origin: "Latin", meaning: "Water" },
    { name: "Wave", origin: "English", meaning: "Ocean wave" },
    { name: "Cobalt", origin: "German", meaning: "Deep blue metal" },
    { name: "Sunny", origin: "English", meaning: "Bright like the sun" },
    { name: "Ripple", origin: "English", meaning: "Water motion" },
    { name: "Glint", origin: "English", meaning: "Sparkle" },
    { name: "Neptune", origin: "Roman Mythology", meaning: "God of the sea" },
    { name: "Tide", origin: "English", meaning: "Ocean movement" }
  ],

  other: [
    { name: "Echo", origin: "Greek Mythology", meaning: "Resonating sound, symbolizing connection and response" },
    { name: "Phoenix", origin: "Greek Mythology", meaning: "Mythical bird of renewal and rebirth" },
    { name: "Cosmos", origin: "Greek", meaning: "Universe or harmony, representing infinite possibilities" },
    { name: "Zephyr", origin: "Greek", meaning: "West wind" },
    { name: "Orion", origin: "Greek Mythology", meaning: "Hunter constellation" },
    { name: "Nimbus", origin: "Latin", meaning: "Rain cloud" },
    { name: "Comet", origin: "Latin", meaning: "Celestial body" },
    { name: "Aurora", origin: "Latin", meaning: "Dawn, northern lights" },
    { name: "Myst", origin: "English", meaning: "Fog or mystery" },
    { name: "Ember", origin: "Old English", meaning: "Glowing coal" },
    { name: "Sirius", origin: "Greek", meaning: "Brightest star" },
    { name: "Lumen", origin: "Latin", meaning: "Light" },
    { name: "Shadow", origin: "English", meaning: "Dark companion" },
    { name: "Indigo", origin: "Greek", meaning: "Deep blue" },
    { name: "Fable", origin: "English", meaning: "Story or legend" },
    { name: "Nova", origin: "Latin", meaning: "New star" },
    { name: "Galaxy", origin: "Greek", meaning: "Milky Way, universe" },
    { name: "Auric", origin: "Latin", meaning: "Golden" },
    { name: "Quest", origin: "English", meaning: "Journey or adventure" },
    { name: "Rune", origin: "Old Norse", meaning: "Mystical symbol" }
  ]
};