'use client';

import { useState } from 'react';

export default function TestDBPage() {
  const [names, setNames] = useState([]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');

  const testFetchNames = async () => {
    setLoading(true);
    setMessage('');
    try {
      const response = await fetch('/api/names');
      const data = await response.json();
      setNames(data);
      setMessage(`Successfully fetched ${data.length} names`);
    } catch (error) {
      setMessage(`Error: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const testAddName = async () => {
    setLoading(true);
    setMessage('');
    try {
      const response = await fetch('/api/names', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: 'TestName',
          meaning: 'A test name for testing purposes',
          origin: 'Test Origin',
          petDescription: 'Test pet',
          petTypes: ['dog'],
          genders: ['male'],
          nameStyles: ['classic']
        }),
      });
      const data = await response.json();
      setMessage(`Successfully added name: ${data.message}`);
      // Refresh the names list
      testFetchNames();
    } catch (error) {
      setMessage(`Error: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const testGenerateNames = async () => {
    setLoading(true);
    setMessage('');
    try {
      const response = await fetch('/api/generate-names', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          petDescription: 'A friendly golden retriever',
          petTypes: ['dog'],
          genders: ['male'],
          nameStyles: ['classic']
        }),
      });
      const data = await response.json();
      setMessage(`Successfully generated ${data.names.length} names`);
      // Refresh the names list
      testFetchNames();
    } catch (error) {
      setMessage(`Error: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto p-8">
      <h1 className="text-3xl font-bold mb-8">Firebase Database Test Page</h1>
      
      <div className="space-y-4 mb-8">
        <button
          onClick={testFetchNames}
          disabled={loading}
          className="bg-blue-500 text-white px-4 py-2 rounded disabled:opacity-50"
        >
          {loading ? 'Loading...' : 'Fetch Names from DB'}
        </button>
        
        <button
          onClick={testAddName}
          disabled={loading}
          className="bg-green-500 text-white px-4 py-2 rounded disabled:opacity-50 ml-4"
        >
          {loading ? 'Loading...' : 'Add Test Name to DB'}
        </button>
        
        <button
          onClick={testGenerateNames}
          disabled={loading}
          className="bg-purple-500 text-white px-4 py-2 rounded disabled:opacity-50 ml-4"
        >
          {loading ? 'Loading...' : 'Generate Names (Save to DB)'}
        </button>
      </div>

      {message && (
        <div className={`p-4 rounded mb-4 ${
          message.startsWith('Error') ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700'
        }`}>
          {message}
        </div>
      )}

      {names.length > 0 && (
        <div>
          <h2 className="text-xl font-semibold mb-4">Names in Database ({names.length})</h2>
          <div className="grid gap-4">
            {names.map((name: any) => (
              <div key={name.id} className="border p-4 rounded">
                <h3 className="font-semibold">{name.name}</h3>
                <p className="text-gray-600">{name.meaning}</p>
                <p className="text-sm text-gray-500">Origin: {name.origin}</p>
                <p className="text-sm text-gray-500">Generated by: {name.generatedBy}</p>
                <p className="text-sm text-gray-500">Created: {new Date(name.createdAt?.toDate?.() || name.createdAt).toLocaleString()}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
